# Generated by Django 4.0 on 2022-01-27 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzy', '0004_alter_project_activity_alter_project_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='activity',
            field=models.ManyToManyField(blank=True, related_name='project', to='buzy.Activity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='in_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
