# Generated by Django 4.0 on 2022-01-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzy', '0006_alter_activity_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=12)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
