# Generated by Django 4.0 on 2022-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzy', '0007_client_producat'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('purchase', 'purchase'), ('refund', 'Refund'), ('custom', 'Custom')], default='custom', max_length=64),
        ),
    ]
