# Generated by Django 4.0 on 2022-02-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzy', '0009_rename_producat_product_project_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='project',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product_projects', to='buzy.Product'),
        ),
    ]
