# Generated by Django 4.0 on 2022-02-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzy', '0010_remove_product_color_alter_project_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='client_projects', to='buzy.Client'),
        ),
    ]
